BBBB BBBBBB

XXXXXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXX
    XXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXX XXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXXXXX
            XXXX XXXXXXXXXXXXXXXXX
                XXXX XXXXXXXXXXXXXXXXX
                    XXXXX XXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXXXXX XXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXX
                        XXX XX XXX
                    XXXXXXX
                    XX XXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXX XXXX XXXXXXXXXXXXXXX
                        XXX XXX XX
                    XXXX
               XXXXXX
                XX XXXXXXXXXXXXXX XXXXXXXXXXXXXX XXXXXX
                    XXXXX XXXXX XXXXX XXX XXXX XXXXXXXXXXXX XXXXXXX XXXX XXXX XXXXXXX XXXXXXXXX XXXXXX XXX
                    XXXXXXX XXXXXXXX XXXXX XX XX XXXXXX XXXXXXXXX XXXXX XXXXXX XXXXXXXX XXXXXXXXX XXX XXXXXXXX
                    XXXXXX XXXXXX XXXXXXX XXXXXXXXXXX XXXXXXX
                    XXXX
                    XXXX
                    XXX XX XXXXXXXXXXXX XXXX XXXXX XXXX XXXXX XXXXX XXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX
                    XXXXXXXXXXX XXXXX XXX XXXXXXXX XXXXX XXXX XXXX XX XXXX XXXXXXXXX XXXXXXXXX XX XXXXX XXXXXXXXXX XXXXXX
                    XXXXX XXXXX XXXX XXXXXXXXXX XXXX XXXX XXXXX XXXXXXXXXX XXXX XXXXXXXX XXX XXXXXXXXXX XXX XXXX XXX XXXXXX
                XXXX
                XXXXXXX
                    XXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXX XXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXX XX XXX XXXXXXX XXXXXXXXXXXXXXXXX
            XXXXXX
            XXXX XXXXXXXXXXXXXXXXX
                XXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXX XXXXXXXXXXX XX
            XXXXXX
    
        XXXXXX
    XXXXXX
XXXXXXXXXX