# Generated by Django 3.2.25 on 2025-03-11 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_payment_reservation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=100)),
                ('pickup_date_time', models.DateTimeField()),
                ('return_date_time', models.DateTimeField()),
                ('date_capture', models.DateTimeField(auto_now_add=True)),
                ('how_people', models.PositiveIntegerField(default=1)),
                ('one_way', models.BooleanField(default=False)),
                ('car_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='core.car')),
                ('dropoff_location1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dropoff_location1_bookings', to='core.hotel')),
                ('dropoff_location2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dropoff_location2_bookings', to='core.hotel')),
                ('pickup_location1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pickup_location1_bookings', to='core.hotel')),
                ('pickup_location2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pickup_location2_bookings', to='core.hotel')),
            ],
        ),
    ]
