# Generated by Django 3.2.25 on 2025-08-29 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cartype_catalog_and_relationships'),
        ('core', '0003_add_customer_fields'),
    ]

    operations = [
    ]
