# Generated by Django 3.2.25 on 2025-12-24 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload certificate image (JPG/PNG). If provided, this will be used instead of the SVG icon.', null=True, upload_to='certificates/'),
        ),
        migrations.AlterField(
            model_name='certificate',
            name='icon_svg',
            field=models.TextField(blank=True, help_text="SVG path element (the 'd' attribute value)", null=True),
        ),
    ]
