# Generated by Django 3.2.25 on 2025-03-12 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20250311_1933'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='max',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
