XXXXXXXXX XXXXX
XXXXX XXXXXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXX

BBBB BBBBBB

XXXXXX
	XXXXX XXXXXXXXXXXXXXXX
	XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXX
	XXXXXXXXXXXXX XXXXXXXXX X XXXXXX XX XXXXXX XXXXXXXXXXXXXXXX
	XXXXX XXXXXXXXXXXXXXXX XXXXXXBBBBBB BBBBBBBBBBBBBBBBXX
	XXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
	XXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXX XX XXXXXX XXXXXXXXX XX
	XXXXX XXXXXXXXXXXXXXX XXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXX XXXXXX XXXXXXXXX XX
	XXXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XX

	XXXX XXXXXXX XXX

	BBBBB BBBBBBBBB BBBBBBBB

XXXXXXX

XXXXXX
    BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBB
    BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBB
    BBBBBBB BBBBBBBBBBBBBBBBBBBBBB
    
    XXXXX XXXXXXXXXXXXXXXX XXXXXXX XXXX XXXXXXX XXXXXXXXXX
        BBBBB BBBBBBB BBBBBBBB
    XXXXXXX

        BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBB
        BBBBBBB BBBBBBBBBBBBBBBBBBBBBBBB
XXXXXXX

BBBBB BBBBBBBB BBBBBBBB

XXXXXXX XXXXXBBBBBB BBBBBBBBBBBBBBBBX XXXXXXXXXXXXXXXXXXXXXXX
XXXXXXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXX
XXX XXXXXXX X XXX XXXXXXXXXXXXXXXXXXXX X
    XXXXXXXXXXX X XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XX
    XXXXXXXXXXXXXX XX
    XXXXXXXXXXXXX XXX
    XXXXX XXXXX
    XXXXXXXXXXXX X
        XXXX X XXXXXXXXXXXXXX XX XXXXXXXXXXXXX XX XX
        XXXX X XXXXXXXXXXXXXX XX XXXXXXXXXXXXX XX XX
        XXXX X XXXXXXXXXXXXXX XX XXXXXXXXXXXXX XX XX
        XXXXX X XXXXXXXXXXXXXX XX XXXXXXXXXXXXX XX XX
    X
XXX
XXX XXXXXXX X XXX XXXXXXXXXXXXXXXXXXXX X
    XXXXXXXXXXX X XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XX
    XXXXXXXXXXXXXX XX
    XXXXXXXXXXXXX XXX
    XXXXX XXXXX
    XXXXXXXXXXXX X
        XXXX X XXXXXXXXXXXXXX XX XXXXXXXXXXXXX XX XX
        XXXX X XXXXXXXXXXXXXX XX XXXXXXXXXXXXX XX XX
        XXXX X XXXXXXXXXXXXXX XX XXXXXXXXXXXXX XX XX
        XXXXX X XXXXXXXXXXXXXX XX XXXXXXXXXXXXX XX XX
    X
XXX
XXX XXXXXXX X XXX XXXXXXXXXXXXXXXXXXXX X
    XXXXXXXXXXX X XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XX
    XXXXXXXXXXXXXX XX
    XXXXXXXXXXXXX XXX
    XXXXX XXXXX
    XXXXXXXXXXXX X
        XXXX X XXXXXXXXXXXXXX XX XXXXXXXXXXXXX XX XX
        XXXX X XXXXXXXXXXXXXX XX XXXXXXXXXXXXX XX XX
        XXXX X XXXXXXXXXXXXXX XX XXXXXXXXXXXXX XX XX
        XXXXX X XXXXXXXXXXXXXX XX XXXXXXXXXXXXX XX XX
    X
XXX
XXX XXXXXXX X XXX XXXXXXXXXXXXXXXXXXXX X
    XXXXXXXXXXX X XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX XXXXXXX XXXXXXXXXXXXXXXXXXXXXX XX
    XXXXXXXXXXXXXX XX
    XXXXXXXXXXXXX XXX
    XXXXX XXXXX
    XXXXXXXXXXXX X
        XXXX X XXXXXXXXXXXXXX XX XXXXXXXXXXXXX XX XX
        XXXX X XXXXXXXXXXXXXX XX XXXXXXXXXXXXX XX XX
        XXXX X XXXXXXXXXXXXXX XX XXXXXXXXXXXXX XX XX
        XXXXX X XXXXXXXXXXXXXX XX XXXXXXXXXXXXX XX XX
    X
XXX
	XXX XXXXXXXXXXXXXXXX X XXX XXXXXXXXXXXXXXXXXXXXXXXXXXXXX X
		XXXXXXXX XXXXX
      XXXXXXXXXXX X
        XXXXXXX XXXXXXXXXXXXXXXXXXXXXX
        XXXXXXX XXXXXXXXXXXXXXXXXXXXXX
      XX
      XXXXXXXXXXX X
        XXX XXXXXXXXXXXXXXXXXXXXX
      XX
      XXXXXXXXXXX XXXXX
      XXXXXXXXX XXXXX
	  XXXXXXXXXX
    XXX

	XXXXXXXX XXXXXXXXXXXXXXX X
            XXXXX XXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXXXXXXXXXXXXXXXXXXXXXXXX XX X
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXX
            XXXXX XXXXXXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXX XXXXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XXXXX XXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            XX XXXXXXXXX X
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
            X
        X
        XXXXX XXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXX XX X
            XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXX
        XXX

        XXXXXXXXXXXXXXXX
XXXXXXXXX

XXXXXXX